# Generated by Django 3.0.3 on 2020-06-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicantregister',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=40)),
                ('gen', models.CharField(max_length=10)),
                ('con', models.IntegerField(primary_key=True, serialize=False)),
                ('addr', models.CharField(max_length=60)),
                ('usrname', models.CharField(max_length=30)),
                ('pas', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Applicanttable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pas', models.CharField(max_length=30)),
            ],
        ),
    ]
